springdoc.swagger-ui.operationsSorter: method
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.open-in-view: false
file.matchjson.location: /path/to/store
file.matchscorecard.location: /path/to/store
spring.jpa.properties.hibernate:
   jdbc.batch_size: 50
   generate_statistics: false
---
spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://localhost:3306/cricketdb?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
      username: root
      password: password
      hikari:
         maximumPoolSize: 10
         idleTimeout: 120000
         connectionTimeout: 300000
         leakDetectionThreshold: 300000
threads: 20
---
spring:
   profiles: prod
   datasource:
      url:
      username:
      password:
threads: 20
---
spring:
   profiles: test
   jpa.hibernate.ddl-auto: create-drop
   datasource: 
      url: jdbc:mysql://localhost:3306/cricketdbtest
      username: root
      password: root
threads: 20
