-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 01:27:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cricket
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cricketdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cricketdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cricketdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cricketdb` ;

-- -----------------------------------------------------
-- Table `cricketdb`.`match_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`match_summary` (
  `match_id` INT NOT NULL,
  `actual_days` INT NULL DEFAULT NULL,
  `adjusted` INT NULL DEFAULT NULL,
  `amount` INT NULL DEFAULT NULL,
  `amount_balls` INT NULL DEFAULT NULL,
  `amount_name` VARCHAR(30) NULL DEFAULT NULL,
  `amount_type` INT NULL DEFAULT NULL,
  `away_team_id` INT NULL DEFAULT NULL,
  `ballbyball_source` VARCHAR(20) NULL DEFAULT NULL,
  `batting_first_team_id` INT NULL DEFAULT NULL,
  `bitly_hash` VARCHAR(10) NULL DEFAULT NULL,
  `bpo` INT NULL DEFAULT NULL,
  `cancelled_match` VARCHAR(10) NULL DEFAULT NULL,
  `cms_match_title` VARCHAR(50) NULL DEFAULT NULL,
  `commentary_source` VARCHAR(30) NULL DEFAULT NULL,
  `continent_id` INT NULL DEFAULT NULL,
  `continent_name` VARCHAR(30) NULL DEFAULT NULL,
  `country_abbreviation` VARCHAR(30) NULL DEFAULT NULL,
  `country_filename` VARCHAR(30) NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  `country_name` VARCHAR(255) NULL DEFAULT NULL,
  `date` VARCHAR(30) NULL DEFAULT NULL,
  `date_string` VARCHAR(100) NULL DEFAULT NULL,
  `days_extended` INT NULL DEFAULT NULL,
  `end_date` VARCHAR(40) NULL DEFAULT NULL,
  `end_date_raw` DATE NULL DEFAULT NULL,
  `floodlit` INT NULL DEFAULT NULL,
  `floodlit_name` VARCHAR(30) NULL DEFAULT NULL,
  `followon` INT NULL DEFAULT NULL,
  `general_class_card` VARCHAR(20) NULL DEFAULT NULL,
  `general_class_id` INT NULL DEFAULT NULL,
  `general_class_name` VARCHAR(30) NULL DEFAULT NULL,
  `general_number` VARCHAR(255) NULL DEFAULT NULL,
  `general_valid` INT NULL DEFAULT NULL,
  `gmt_difference` VARCHAR(10) NULL DEFAULT NULL,
  `ground_id` INT NULL DEFAULT NULL,
  `ground_latitude` VARCHAR(20) NULL DEFAULT NULL,
  `ground_longitude` VARCHAR(20) NULL DEFAULT NULL,
  `ground_name` VARCHAR(255) NULL DEFAULT NULL,
  `ground_object_id` INT NULL DEFAULT NULL,
  `ground_small_name` VARCHAR(50) NULL DEFAULT NULL,
  `hawkeye_source` VARCHAR(30) NULL DEFAULT NULL,
  `head2head_source` VARCHAR(30) NULL DEFAULT NULL,
  `home_team_id` INT NULL DEFAULT NULL,
  `hours_string` TEXT NULL DEFAULT NULL,
  `international_class_card` VARCHAR(20) NULL DEFAULT NULL,
  `international_class_id` INT NULL DEFAULT NULL,
  `international_class_name` VARCHAR(30) NULL DEFAULT NULL,
  `international_number` INT NULL DEFAULT NULL,
  `international_valid` INT NULL DEFAULT NULL,
  `legacy_url` TEXT NULL DEFAULT NULL,
  `live_commentator` VARCHAR(50) NULL DEFAULT NULL,
  `live_companion` VARCHAR(30) NULL DEFAULT NULL,
  `live_day_number` INT NULL DEFAULT NULL,
  `live_innings_number` INT NULL DEFAULT NULL,
  `live_match` VARCHAR(10) NULL DEFAULT NULL,
  `live_note` VARCHAR(40) NULL DEFAULT NULL,
  `live_overs_remaining` DOUBLE NOT NULL,
  `live_overs_unique` DOUBLE NOT NULL,
  `live_scorer` VARCHAR(40) NULL DEFAULT NULL,
  `live_session_number` INT NULL DEFAULT NULL,
  `live_state` VARCHAR(100) NULL DEFAULT NULL,
  `match_clock` VARCHAR(40) NULL DEFAULT NULL,
  `match_day_countdown` INT NULL DEFAULT NULL,
  `match_minute_countdown` INT NULL DEFAULT NULL,
  `match_path` TEXT NULL DEFAULT NULL,
  `match_status` VARCHAR(15) NULL DEFAULT NULL,
  `neutral_match` INT NULL DEFAULT NULL,
  `next_datetime_gmt` DATETIME(6) NULL DEFAULT NULL,
  `next_datetime_local` DATETIME(6) NULL DEFAULT NULL,
  `player_rating` VARCHAR(10) NULL DEFAULT NULL,
  `present_date_gmt` DATE NULL DEFAULT NULL,
  `present_date_local` DATE NULL DEFAULT NULL,
  `present_datetime_gmt` DATETIME(6) NULL DEFAULT NULL,
  `present_datetime_local` DATETIME(6) NULL DEFAULT NULL,
  `present_time_gmt` TIME NULL DEFAULT NULL,
  `present_time_local` TIME NULL DEFAULT NULL,
  `rain_rule` INT NULL DEFAULT NULL,
  `rain_rule_name` VARCHAR(255) NULL DEFAULT NULL,
  `rating_promo` VARCHAR(255) NULL DEFAULT NULL,
  `reduced` INT NULL DEFAULT NULL,
  `reserve_days_used` INT NULL DEFAULT NULL,
  `result` INT NULL DEFAULT NULL,
  `result_name` VARCHAR(255) NULL DEFAULT NULL,
  `result_short_name` VARCHAR(15) NULL DEFAULT NULL,
  `schedule_note` VARCHAR(50) NULL DEFAULT NULL,
  `scheduled_days` INT NULL DEFAULT NULL,
  `scheduled_innings` INT NULL DEFAULT NULL,
  `scheduled_overs` DOUBLE NOT NULL,
  `scorecard_source` VARCHAR(15) NULL DEFAULT NULL,
  `scribble_id` INT NULL DEFAULT NULL,
  `season` VARCHAR(255) NULL DEFAULT NULL,
  `site_id` INT NULL DEFAULT NULL,
  `site_name` VARCHAR(50) NULL DEFAULT NULL,
  `start_date` VARCHAR(20) NULL DEFAULT NULL,
  `start_date_gmt_offset` VARCHAR(20) NULL DEFAULT NULL,
  `start_date_raw` DATE NULL DEFAULT NULL,
  `start_datetime_gmt` DATETIME(6) NULL DEFAULT NULL,
  `start_datetime_gmt_raw` DATETIME(6) NULL DEFAULT NULL,
  `start_datetime_local` DATETIME(6) NULL DEFAULT NULL,
  `start_time_gmt` TIME NULL DEFAULT NULL,
  `start_time_local` TIME NULL DEFAULT NULL,
  `sub_class_id` INT NULL DEFAULT NULL,
  `team1abbreviation` VARCHAR(15) NULL DEFAULT NULL,
  `team1class_id` INT NULL DEFAULT NULL,
  `team1country_id` INT NULL DEFAULT NULL,
  `team1filename` VARCHAR(20) NULL DEFAULT NULL,
  `team1id` INT NULL DEFAULT NULL,
  `team1logo_alt_id` VARCHAR(10) NULL DEFAULT NULL,
  `team1logo_espncdn` VARCHAR(10) NULL DEFAULT NULL,
  `team1logo_object_id` INT NULL DEFAULT NULL,
  `team1name` VARCHAR(50) NULL DEFAULT NULL,
  `team1object_id` INT NULL DEFAULT NULL,
  `team1short_name` VARCHAR(20) NULL DEFAULT NULL,
  `team2abbreviation` VARCHAR(10) NULL DEFAULT NULL,
  `team2class_id` INT NULL DEFAULT NULL,
  `team2country_id` INT NULL DEFAULT NULL,
  `team2filename` VARCHAR(20) NULL DEFAULT NULL,
  `team2id` INT NULL DEFAULT NULL,
  `team2logo_alt_id` VARCHAR(10) NULL DEFAULT NULL,
  `team2logo_espncdn` VARCHAR(10) NULL DEFAULT NULL,
  `team2logo_object_id` INT NULL DEFAULT NULL,
  `team2name` VARCHAR(50) NULL DEFAULT NULL,
  `team2object_id` INT NULL DEFAULT NULL,
  `team2short_name` VARCHAR(20) NULL DEFAULT NULL,
  `tiebreaker_name` VARCHAR(20) NULL DEFAULT NULL,
  `tiebreaker_team_id` INT NULL DEFAULT NULL,
  `tiebreaker_type` INT NULL DEFAULT NULL,
  `time_zone` VARCHAR(30) NULL DEFAULT NULL,
  `toss_choice_team_id` INT NULL DEFAULT NULL,
  `toss_decision` INT NULL DEFAULT NULL,
  `toss_decision_name` VARCHAR(20) NULL DEFAULT NULL,
  `toss_winner_team_id` INT NOT NULL,
  `town_aka` VARCHAR(255) NULL DEFAULT NULL,
  `town_area` VARCHAR(30) NULL DEFAULT NULL,
  `town_id` INT NOT NULL,
  `town_name` VARCHAR(50) NULL DEFAULT NULL,
  `tz_short_name` VARCHAR(10) NULL DEFAULT NULL,
  `url_component` VARCHAR(50) NULL DEFAULT NULL,
  `watch_espn_id` INT NOT NULL,
  `weather_location_code` VARCHAR(20) NULL DEFAULT NULL,
  `winner_team_id` INT NOT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`batting_scorecard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`batting_scorecard` (
  `batsman_id` INT NOT NULL,
  `innings` INT NOT NULL,
  `balls` INT NULL DEFAULT NULL,
  `batted_type` VARCHAR(255) NULL DEFAULT NULL,
  `dismissal_type` INT NULL DEFAULT NULL,
  `fours` INT NULL DEFAULT NULL,
  `is_out` BIT(1) NULL DEFAULT NULL,
  `minutes` INT NULL DEFAULT NULL,
  `player_role_type` VARCHAR(255) NULL DEFAULT NULL,
  `position` INT NULL DEFAULT NULL,
  `runs` INT NULL DEFAULT NULL,
  `sixes` INT NULL DEFAULT NULL,
  `strikerate` DOUBLE NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`batsman_id`, `innings`, `match_id`),
  INDEX `FKepa4hnwabt9n1p7desl78slsg` (`match_id` ASC),
  CONSTRAINT `FKepa4hnwabt9n1p7desl78slsg`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`bowling_scorecard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`bowling_scorecard` (
  `bowler_id` INT NOT NULL,
  `innings` INT NOT NULL,
  `balls` INT NULL DEFAULT NULL,
  `conceded` INT NULL DEFAULT NULL,
  `dots` INT NULL DEFAULT NULL,
  `economy` DOUBLE NULL DEFAULT NULL,
  `fours` INT NULL DEFAULT NULL,
  `maidens` INT NULL DEFAULT NULL,
  `noballs` INT NULL DEFAULT NULL,
  `overs` DOUBLE NULL DEFAULT NULL,
  `position` INT NULL DEFAULT NULL,
  `runs_per_ball` DOUBLE NULL DEFAULT NULL,
  `sixes` INT NULL DEFAULT NULL,
  `wickets` INT NULL DEFAULT NULL,
  `wides` INT NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`bowler_id`, `innings`, `match_id`),
  INDEX `FKt71jlpgkt8jkrbtkduq6agvju` (`match_id` ASC),
  CONSTRAINT `FKt71jlpgkt8jkrbtkduq6agvju`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`debuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`debuts` (
  `class_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`class_id`, `match_id`, `object_id`),
  INDEX `FK7e7xw0b5ld9faq2iujx8cwyw2` (`match_id` ASC),
  CONSTRAINT `FK7e7xw0b5ld9faq2iujx8cwyw2`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`fow_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`fow_summary` (
  `batsman_id` INT NOT NULL,
  `fow_wicket_num` INT NOT NULL,
  `innings` INT NOT NULL,
  `ball_batsman_runs` INT NULL DEFAULT NULL,
  `ball_overs_actual` DOUBLE NULL DEFAULT NULL,
  `ball_total_runs` INT NULL DEFAULT NULL,
  `batted_type` VARCHAR(255) NULL DEFAULT NULL,
  `bowler_id` INT NULL DEFAULT NULL,
  `dismissal_text_long` VARCHAR(255) NULL DEFAULT NULL,
  `dismissal_text_short` VARCHAR(255) NULL DEFAULT NULL,
  `dismissal_type` INT NULL DEFAULT NULL,
  `fielder1id` INT NULL DEFAULT NULL,
  `fielder2id` INT NULL DEFAULT NULL,
  `fielder3id` INT NULL DEFAULT NULL,
  `fielder4id` INT NULL DEFAULT NULL,
  `fow_balls` INT NULL DEFAULT NULL,
  `fow_order` INT NULL DEFAULT NULL,
  `fow_over_number` INT NULL DEFAULT NULL,
  `fow_overs` DOUBLE NULL DEFAULT NULL,
  `fow_runs` INT NULL DEFAULT NULL,
  `is_keeper` INT NULL DEFAULT NULL,
  `is_substitute` INT NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`batsman_id`, `fow_wicket_num`, `innings`, `match_id`),
  INDEX `FKbvhkfae7odhhgd4o9v4eqijbf` (`match_id` ASC),
  CONSTRAINT `FKbvhkfae7odhhgd4o9v4eqijbf`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`match_innings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`match_innings` (
  `innings_number` INT NOT NULL,
  `ball_limit` INT NULL DEFAULT NULL,
  `balls` INT NULL DEFAULT NULL,
  `batted` INT NULL DEFAULT NULL,
  `batting_team_id` INT NULL DEFAULT NULL,
  `bowling_team_id` INT NULL DEFAULT NULL,
  `bpo` INT NULL DEFAULT NULL,
  `byes` INT NULL DEFAULT NULL,
  `event` INT NULL DEFAULT NULL,
  `event_name` VARCHAR(255) NULL DEFAULT NULL,
  `extras` INT NULL DEFAULT NULL,
  `innings_numth` VARCHAR(255) NULL DEFAULT NULL,
  `leadby` INT NULL DEFAULT NULL,
  `legbyes` INT NULL DEFAULT NULL,
  `live_current` INT NULL DEFAULT NULL,
  `live_current_name` VARCHAR(255) NULL DEFAULT NULL,
  `minutes` INT NULL DEFAULT NULL,
  `noballs` INT NULL DEFAULT NULL,
  `old_penalty_or_bonus` INT NULL DEFAULT NULL,
  `over_limit` DOUBLE NULL DEFAULT NULL,
  `over_limit_run_rate` VARCHAR(255) NULL DEFAULT NULL,
  `over_split_limit` VARCHAR(255) NULL DEFAULT NULL,
  `overs` DOUBLE NULL DEFAULT NULL,
  `overs_docked` INT NULL DEFAULT NULL,
  `penalties` INT NULL DEFAULT NULL,
  `penalties_field_end` INT NULL DEFAULT NULL,
  `penalties_field_start` INT NULL DEFAULT NULL,
  `run_rate` DOUBLE NULL DEFAULT NULL,
  `runs` INT NULL DEFAULT NULL,
  `target` INT NULL DEFAULT NULL,
  `wickets` INT NULL DEFAULT NULL,
  `wides` INT NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`innings_number`, `match_id`),
  INDEX `FKgipnlgvnb8pnqnaymtqr7g0tl` (`match_id` ASC),
  CONSTRAINT `FKgipnlgvnb8pnqnaymtqr7g0tl`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`official_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`official_summary` (
  `object_id` INT NOT NULL,
  `player_type` INT NOT NULL,
  `team_id` INT NOT NULL,
  `age_days` INT NULL DEFAULT NULL,
  `age_years` INT NULL DEFAULT NULL,
  `alpha_name` VARCHAR(50) NULL DEFAULT NULL,
  `batting_hand` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_hand` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_pacespin` VARCHAR(40) NULL DEFAULT NULL,
  `card_long` VARCHAR(40) NULL DEFAULT NULL,
  `card_qualifier` VARCHAR(40) NULL DEFAULT NULL,
  `card_short` VARCHAR(40) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `known_as` VARCHAR(100) NULL DEFAULT NULL,
  `mobile_name` VARCHAR(50) NULL DEFAULT NULL,
  `player_id` INT NULL DEFAULT NULL,
  `player_type_name` VARCHAR(50) NULL DEFAULT NULL,
  `popular_name` VARCHAR(50) NULL DEFAULT NULL,
  `portrait_alt_id` VARCHAR(30) NULL DEFAULT NULL,
  `portrait_object_id` INT NULL DEFAULT NULL,
  `status_id` INT NULL DEFAULT NULL,
  `team_abbreviation` VARCHAR(255) NULL DEFAULT NULL,
  `team_name` VARCHAR(255) NULL DEFAULT NULL,
  `team_short_name` VARCHAR(255) NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `object_id`, `player_type`, `team_id`),
  CONSTRAINT `FKrq2owyfd8ujtwtn1bk93qg4a6`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`partnership_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`partnership_summary` (
  `innings` INT NOT NULL,
  `player1id` INT NOT NULL,
  `player2id` INT NOT NULL,
  `wicket_number` INT NOT NULL,
  `balls` INT NULL DEFAULT NULL,
  `out_player_id` INT NULL DEFAULT NULL,
  `out_player_object_id` INT NULL DEFAULT NULL,
  `overs` DOUBLE NULL DEFAULT NULL,
  `player1balls` INT NULL DEFAULT NULL,
  `player1runs` INT NULL DEFAULT NULL,
  `player2balls` INT NULL DEFAULT NULL,
  `player2runs` INT NULL DEFAULT NULL,
  `runs` INT NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`innings`, `match_id`, `player1id`, `player2id`, `wicket_number`),
  INDEX `FKjxekrjkoqn4j9b96i1jb4tu2i` (`match_id` ASC),
  CONSTRAINT `FKjxekrjkoqn4j9b96i1jb4tu2i`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`players_of_the_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`players_of_the_match` (
  `object_id` INT NOT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `object_id`),
  CONSTRAINT `FK1xg7qp8vjv6o5pj1v3hjssg2o`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`players_of_the_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`players_of_the_series` (
  `object_id` INT NOT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `object_id`),
  CONSTRAINT `FKc6lpo5ncgadhfshwl5uygdp2i`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`replacement_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`replacement_summary` (
  `object_id` INT NOT NULL,
  `innings` INT NULL DEFAULT NULL,
  `overs` DOUBLE NULL DEFAULT NULL,
  `replacing_player_id` INT NULL DEFAULT NULL,
  `team_id` INT NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `object_id`),
  CONSTRAINT `FKolk4aon0dvh09d2k7fvyxchsw`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`results_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`results_summary` (
  `match_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `ground` VARCHAR(255) NULL DEFAULT NULL,
  `ground_id` INT NOT NULL,
  `margin` VARCHAR(255) NULL DEFAULT NULL,
  `match_date` VARCHAR(255) NULL DEFAULT NULL,
  `scorecard` VARCHAR(255) NULL DEFAULT NULL,
  `team1` VARCHAR(255) NULL DEFAULT NULL,
  `team2` VARCHAR(255) NULL DEFAULT NULL,
  `winner` VARCHAR(255) NULL DEFAULT NULL,
  `year` INT NOT NULL,
  `match_json_url` VARCHAR(255) NULL DEFAULT NULL,
  `match_number` INT NOT NULL,
  `match_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`series` (
  `core_recreation_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  `class_id` INT NULL DEFAULT NULL,
  `class_name` VARCHAR(50) NULL DEFAULT NULL,
  `content_id` INT NULL DEFAULT NULL,
  `date` VARCHAR(30) NULL DEFAULT NULL,
  `end_date` VARCHAR(20) NULL DEFAULT NULL,
  `end_date_raw` DATE NULL DEFAULT NULL,
  `final_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `group_title` VARCHAR(30) NULL DEFAULT NULL,
  `major_trophy` INT NULL DEFAULT NULL,
  `match_number` INT NULL DEFAULT NULL,
  `match_title` VARCHAR(30) NULL DEFAULT NULL,
  `match_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `multiformat_pointstable` VARCHAR(10) NULL DEFAULT NULL,
  `number_of_hosts` INT NULL DEFAULT NULL,
  `number_of_matches` INT NULL DEFAULT NULL,
  `number_of_teams` INT NULL DEFAULT NULL,
  `points` INT NULL DEFAULT NULL,
  `primary_series` VARCHAR(10) NULL DEFAULT NULL,
  `replayed_date` VARCHAR(20) NULL DEFAULT NULL,
  `schedule_note` VARCHAR(255) NULL DEFAULT NULL,
  `score_module_position` INT NULL DEFAULT NULL,
  `season` VARCHAR(15) NULL DEFAULT NULL,
  `series_abbreviation` VARCHAR(15) NULL DEFAULT NULL,
  `series_category_id` INT NULL DEFAULT NULL,
  `series_category_name` VARCHAR(30) NULL DEFAULT NULL,
  `series_filename` VARCHAR(50) NULL DEFAULT NULL,
  `series_lead_abandoned` INT NULL DEFAULT NULL,
  `series_lead_cancelled` INT NULL DEFAULT NULL,
  `series_lead_how_won_name` VARCHAR(20) NULL DEFAULT NULL,
  `series_lead_lost` INT NULL DEFAULT NULL,
  `series_lead_result_name` VARCHAR(20) NULL DEFAULT NULL,
  `series_lead_team_name` VARCHAR(50) NULL DEFAULT NULL,
  `series_lead_total` INT NULL DEFAULT NULL,
  `series_lead_type_name` VARCHAR(20) NULL DEFAULT NULL,
  `series_lead_won` INT NULL DEFAULT NULL,
  `series_long_description` TEXT NULL DEFAULT NULL,
  `series_name` VARCHAR(255) NULL DEFAULT NULL,
  `series_short_name` VARCHAR(60) NULL DEFAULT NULL,
  `series_status` VARCHAR(30) NULL DEFAULT NULL,
  `series_type_id` INT NULL DEFAULT NULL,
  `series_type_name` VARCHAR(60) NULL DEFAULT NULL,
  `short_alternate_name` VARCHAR(60) NULL DEFAULT NULL,
  `site_id` INT NULL DEFAULT NULL,
  `slug` TEXT NULL DEFAULT NULL,
  `start_date` VARCHAR(50) NULL DEFAULT NULL,
  `start_date_raw` DATE NULL DEFAULT NULL,
  `team1points` DOUBLE NOT NULL,
  `team2points` DOUBLE NOT NULL,
  `tiebreaker_id` INT NULL DEFAULT NULL,
  `tiebreaker_name` VARCHAR(255) NULL DEFAULT NULL,
  `trophy_abbreviation` VARCHAR(30) NULL DEFAULT NULL,
  `trophy_class_id` INT NULL DEFAULT NULL,
  `trophy_country_id` INT NULL DEFAULT NULL,
  `trophy_id` INT NULL DEFAULT NULL,
  `trophy_name` VARCHAR(255) NULL DEFAULT NULL,
  `trophy_short_name` VARCHAR(50) NULL DEFAULT NULL,
  `url_component` VARCHAR(50) NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`core_recreation_id`, `match_id`, `object_id`),
  INDEX `FKln2gmw4xib4uypnjymoiia37g` (`match_id` ASC),
  CONSTRAINT `FKln2gmw4xib4uypnjymoiia37g`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricketdb`.`squad_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricketdb`.`squad_summary` (
  `object_id` INT NOT NULL,
  `player_type` INT NOT NULL,
  `team_id` INT NOT NULL,
  `age_days` INT NULL DEFAULT NULL,
  `age_years` INT NULL DEFAULT NULL,
  `alpha_name` VARCHAR(50) NULL DEFAULT NULL,
  `batting_hand` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_hand` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_pacespin` VARCHAR(40) NULL DEFAULT NULL,
  `card_long` VARCHAR(40) NULL DEFAULT NULL,
  `card_qualifier` VARCHAR(40) NULL DEFAULT NULL,
  `card_short` VARCHAR(40) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `known_as` VARCHAR(100) NULL DEFAULT NULL,
  `mobile_name` VARCHAR(50) NULL DEFAULT NULL,
  `player_id` INT NULL DEFAULT NULL,
  `player_type_name` VARCHAR(50) NULL DEFAULT NULL,
  `popular_name` VARCHAR(50) NULL DEFAULT NULL,
  `portrait_alt_id` VARCHAR(30) NULL DEFAULT NULL,
  `portrait_object_id` INT NULL DEFAULT NULL,
  `status_id` INT NULL DEFAULT NULL,
  `batting_style` VARCHAR(50) NULL DEFAULT NULL,
  `batting_style_long` VARCHAR(255) NULL DEFAULT NULL,
  `bowling_style` VARCHAR(50) NULL DEFAULT NULL,
  `bowling_style_long` VARCHAR(255) NULL DEFAULT NULL,
  `captain` INT NULL DEFAULT NULL,
  `full_sub` INT NULL DEFAULT NULL,
  `full_sub_innings` INT NULL DEFAULT NULL,
  `full_sub_name` VARCHAR(30) NULL DEFAULT NULL,
  `full_sub_overs` DOUBLE NULL DEFAULT NULL,
  `full_sub_player_id` INT NULL DEFAULT NULL,
  `keeper` INT NULL DEFAULT NULL,
  `player_primary_role` VARCHAR(30) NULL DEFAULT NULL,
  `player_style_id` INT NULL DEFAULT NULL,
  `team_name` VARCHAR(30) NULL DEFAULT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `object_id`, `player_type`, `team_id`),
  CONSTRAINT `FK2tfpehlfh310w4c2ybbbfitqi`
    FOREIGN KEY (`match_id`)
    REFERENCES `cricketdb`.`match_summary` (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
