-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 01:29:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cricket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cricket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cricket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema cricketdb
-- -----------------------------------------------------
USE `cricket` ;

-- -----------------------------------------------------
-- Table `cricket`.`abandoned_cancelled_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`abandoned_cancelled_summary` (
  `team1` VARCHAR(20) NOT NULL,
  `team2` VARCHAR(20) NOT NULL,
  `ground` VARCHAR(45) NOT NULL,
  `match_date` VARCHAR(45) NOT NULL,
  `scorecard` VARCHAR(20) NOT NULL,
  `year` INT NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `match_id` INT NOT NULL,
  `ground_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`match_id`),
  UNIQUE INDEX `match_id_UNIQUE` (`match_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`batting_scorecard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`batting_scorecard` (
  `match_id` INT NOT NULL,
  `innings` INT NOT NULL,
  `batting_team` VARCHAR(40) NOT NULL,
  `bowling_team` VARCHAR(40) NOT NULL,
  `batting_team_id` INT NOT NULL,
  `bowling_team_id` INT NOT NULL,
  `batsman_name` VARCHAR(40) NOT NULL,
  `batsman_display_name` VARCHAR(40) NOT NULL,
  `batsman_id` INT NOT NULL,
  `captain` TINYINT(1) NOT NULL,
  `not_out` TINYINT(1) NULL DEFAULT NULL,
  `runs` INT NULL DEFAULT NULL,
  `balls` INT NULL DEFAULT NULL,
  `minutes` INT NULL DEFAULT NULL,
  `fours` INT NULL DEFAULT NULL,
  `sixes` INT NULL DEFAULT NULL,
  `strike_rate` DOUBLE NULL DEFAULT NULL,
  `runningScore` VARCHAR(20) NULL DEFAULT NULL,
  `shortText` VARCHAR(45) NULL DEFAULT NULL,
  `commentary` TEXT NULL DEFAULT NULL,
  `runningOver` VARCHAR(30) NULL DEFAULT NULL,
  `role` VARCHAR(20) NULL DEFAULT NULL,
  `position` INT NULL DEFAULT NULL,
  `dismissal_type` VARCHAR(45) NULL DEFAULT NULL,
  `fielder1_id` INT NULL DEFAULT NULL,
  `fielder2_id` INT NULL DEFAULT NULL,
  `fielder3_id` INT NULL DEFAULT NULL,
  `dis_keeper` TINYINT(1) NULL DEFAULT NULL,
  `bowler_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`, `innings`, `batting_team_id`, `batsman_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`bowling_scorecard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`bowling_scorecard` (
  `match_id` INT NOT NULL,
  `innings` INT NOT NULL,
  `batting_team` VARCHAR(40) NOT NULL,
  `bowling_team` VARCHAR(40) NOT NULL,
  `batting_team_id` INT NOT NULL,
  `bowling_team_id` INT NOT NULL,
  `bowler_name` VARCHAR(40) NOT NULL,
  `bowler_display_name` VARCHAR(40) NOT NULL,
  `bowler_id` INT NOT NULL,
  `captain` TINYINT(1) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `position` INT NULL DEFAULT NULL,
  `overs` DOUBLE NOT NULL,
  `maidens` INT NULL DEFAULT NULL,
  `conceded` INT NULL DEFAULT NULL,
  `wickets` INT NULL DEFAULT NULL,
  `economy` DOUBLE NULL DEFAULT NULL,
  `dots` INT NULL DEFAULT NULL,
  `fours_conceded` INT NULL DEFAULT NULL,
  `sixes_conceded` INT NULL DEFAULT NULL,
  `wides` INT NULL DEFAULT NULL,
  `noballs` INT NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`, `innings`, `bowler_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`competitors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`competitors` (
  `match_id` INT NOT NULL,
  `batsmen_in_side` INT NULL DEFAULT NULL,
  `content_id` INT NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  `fielders_in_side` INT NULL DEFAULT NULL,
  `object_id` INT NOT NULL,
  `players_in_side` INT NULL DEFAULT NULL,
  `site_id` INT NULL DEFAULT NULL,
  `team_abbreviation` VARCHAR(20) NULL DEFAULT NULL,
  `team_filename` VARCHAR(30) NULL DEFAULT NULL,
  `team_general_name` VARCHAR(30) NULL DEFAULT NULL,
  `team_id` INT NULL DEFAULT NULL,
  `team_name` VARCHAR(40) NULL DEFAULT NULL,
  `team_short_name` VARCHAR(40) NULL DEFAULT NULL,
  `url_component` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`, `object_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`debuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`debuts` (
  `match_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `player_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`dummy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`dummy` (
  `id` INT NULL DEFAULT NULL,
  `value` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`fow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`fow` (
  `match_id` INT NOT NULL,
  `innings` INT NOT NULL,
  `wicket` INT NOT NULL,
  `score` INT NOT NULL,
  `batsman` VARCHAR(40) NULL DEFAULT NULL,
  `batsman_id` INT NULL DEFAULT NULL,
  `over` DOUBLE NULL DEFAULT NULL,
  `notes` VARCHAR(40) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`general_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`general_summary` (
  `team1` VARCHAR(20) NOT NULL,
  `team2` VARCHAR(20) NOT NULL,
  `winner` VARCHAR(20) NOT NULL,
  `margin` VARCHAR(20) NULL DEFAULT NULL,
  `ground` VARCHAR(45) NOT NULL,
  `match_date` VARCHAR(45) NOT NULL,
  `scorecard` VARCHAR(20) NOT NULL,
  `year` INT NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `match_id` INT NOT NULL,
  `ground_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`match_id`),
  UNIQUE INDEX `match_id_UNIQUE` (`match_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`match_innings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`match_innings` (
  `match_id` INT NOT NULL,
  `ball_limit` INT NOT NULL,
  `balls` INT NOT NULL,
  `batted` INT NOT NULL,
  `batting_team_id` INT NOT NULL,
  `bowling_team_id` INT NOT NULL,
  `bpo` INT NOT NULL,
  `byes` INT NOT NULL,
  `event` INT NOT NULL,
  `event_name` VARCHAR(30) NOT NULL,
  `extras` INT NOT NULL,
  `innings_number` INT NOT NULL,
  `innings_numth` VARCHAR(10) NOT NULL,
  `lead` INT NOT NULL,
  `legbyes` INT NULL DEFAULT NULL,
  `minutes` INT NULL DEFAULT NULL,
  `live_current` INT NULL DEFAULT NULL,
  `live_current_name` VARCHAR(45) NULL DEFAULT NULL,
  `noballs` INT NOT NULL,
  `old_penalty_or_bonus` INT NOT NULL,
  `over_limit` DOUBLE NOT NULL,
  `over_limit_run_rate` DOUBLE NOT NULL,
  `over_split_limit` DOUBLE NOT NULL,
  `overs` DOUBLE NOT NULL,
  `overs_docked` INT NOT NULL,
  `penalties` INT NOT NULL,
  `penalties_field_end` INT NOT NULL,
  `penalties_field_start` INT NOT NULL,
  `run_rate` DOUBLE NOT NULL,
  `runs` INT NOT NULL,
  `target` INT NOT NULL,
  `wickets` INT NOT NULL,
  `wides` INT NOT NULL,
  PRIMARY KEY (`match_id`, `innings_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`match_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`match_summary` (
  `match_id` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `actual_days` INT NULL DEFAULT NULL,
  `adjusted` INT NULL DEFAULT NULL,
  `amount` INT NULL DEFAULT NULL,
  `amount_balls` INT NULL DEFAULT NULL,
  `amount_name` VARCHAR(30) NULL DEFAULT NULL,
  `amount_type` INT NULL DEFAULT NULL,
  `away_team_id` INT NULL DEFAULT NULL,
  `ballbyball_source` VARCHAR(30) NULL DEFAULT NULL,
  `batting_first_team_id` INT NULL DEFAULT NULL,
  `bitly_hash` VARCHAR(20) NULL DEFAULT NULL,
  `cancelled_match` VARCHAR(30) NULL DEFAULT NULL,
  `cms_match_title` VARCHAR(30) NULL DEFAULT NULL,
  `commentary_source` VARCHAR(30) NULL DEFAULT NULL,
  `continent_id` INT NULL DEFAULT NULL,
  `continent_name` VARCHAR(30) NULL DEFAULT NULL,
  `country_abbreviation` VARCHAR(20) NULL DEFAULT NULL,
  `country_filename` VARCHAR(45) NULL DEFAULT NULL,
  `country_id` VARCHAR(20) NULL DEFAULT NULL,
  `country_name` VARCHAR(30) NULL DEFAULT NULL,
  `date` VARCHAR(20) NULL DEFAULT NULL,
  `date_string` VARCHAR(40) NULL DEFAULT NULL,
  `days_extended` INT NULL DEFAULT NULL,
  `end_date` VARCHAR(45) NULL DEFAULT NULL,
  `end_date_raw` DATE NULL DEFAULT NULL,
  `floodlit` INT NULL DEFAULT NULL,
  `floodlit_name` VARCHAR(45) NULL DEFAULT NULL,
  `followon` INT NULL DEFAULT NULL,
  `general_class_card` VARCHAR(20) NULL DEFAULT NULL,
  `general_class_id` VARCHAR(20) NULL DEFAULT NULL,
  `general_class_name` VARCHAR(20) NULL DEFAULT NULL,
  `general_number` VARCHAR(20) NULL DEFAULT NULL,
  `general_valid` INT NULL DEFAULT NULL,
  `gmt_difference` VARCHAR(20) NULL DEFAULT NULL,
  `ground_id` INT NULL DEFAULT NULL,
  `ground_latitude` VARCHAR(20) NULL DEFAULT NULL,
  `ground_longitude` VARCHAR(20) NULL DEFAULT NULL,
  `ground_name` TEXT NULL DEFAULT NULL,
  `ground_object_id` INT NULL DEFAULT NULL,
  `ground_small_name` VARCHAR(45) NULL DEFAULT NULL,
  `hawkeye_source` VARCHAR(20) NULL DEFAULT NULL,
  `head2head_source` VARCHAR(20) NULL DEFAULT NULL,
  `home_team_id` INT NULL DEFAULT NULL,
  `hours_string` TEXT NULL DEFAULT NULL,
  `international_class_card` VARCHAR(20) NULL DEFAULT NULL,
  `international_class_id` INT NULL DEFAULT NULL,
  `international_class_name` VARCHAR(45) NULL DEFAULT NULL,
  `international_number` VARCHAR(20) NULL DEFAULT NULL,
  `international_valid` INT NULL DEFAULT NULL,
  `legacy_url` TEXT NULL DEFAULT NULL,
  `live_commentator` VARCHAR(45) NULL DEFAULT NULL,
  `live_companion` VARCHAR(45) NULL DEFAULT NULL,
  `live_day_number` INT NULL DEFAULT NULL,
  `live_innings_number` INT NULL DEFAULT NULL,
  `live_match` VARCHAR(45) NULL DEFAULT NULL,
  `live_note` VARCHAR(45) NULL DEFAULT NULL,
  `live_overs_remaining` DOUBLE NULL DEFAULT NULL,
  `live_overs_unique` DOUBLE NULL DEFAULT NULL,
  `live_scorer` VARCHAR(45) NULL DEFAULT NULL,
  `live_session_number` INT NULL DEFAULT NULL,
  `live_state` VARCHAR(45) NULL DEFAULT NULL,
  `match_clock` VARCHAR(45) NULL DEFAULT NULL,
  `match_day_countdown` VARCHAR(20) NULL DEFAULT NULL,
  `match_minute_countdown` VARCHAR(45) NULL DEFAULT NULL,
  `match_path` TEXT NULL DEFAULT NULL,
  `match_status` VARCHAR(45) NULL DEFAULT NULL,
  `neutral_match` INT NULL DEFAULT NULL,
  `next_datetime_gmt` DATE NULL DEFAULT NULL,
  `next_datetime_local` DATE NULL DEFAULT NULL,
  `player_rating` VARCHAR(20) NULL DEFAULT NULL,
  `present_date_gmt` DATE NULL DEFAULT NULL,
  `present_date_local` DATE NULL DEFAULT NULL,
  `present_datetime_gmt` DATETIME NULL DEFAULT NULL,
  `present_datetime_local` DATETIME NULL DEFAULT NULL,
  `present_time_gmt` TIME NULL DEFAULT NULL,
  `present_time_local` TIME NULL DEFAULT NULL,
  `rain_rule` INT NULL DEFAULT NULL,
  `rain_rule_name` VARCHAR(20) NULL DEFAULT NULL,
  `rating_promo` VARCHAR(20) NULL DEFAULT NULL,
  `reduced` INT NULL DEFAULT NULL,
  `reserve_days_used` INT NULL DEFAULT NULL,
  `result` INT NULL DEFAULT NULL,
  `result_name` VARCHAR(50) NULL DEFAULT NULL,
  `result_short_name` VARCHAR(20) NULL DEFAULT NULL,
  `schedule_note` VARCHAR(40) NULL DEFAULT NULL,
  `scheduled_days` INT NULL DEFAULT NULL,
  `scheduled_innings` INT NULL DEFAULT NULL,
  `scheduled_overs` INT NULL DEFAULT NULL,
  `scorecard_source` VARCHAR(30) NULL DEFAULT NULL,
  `scribble_id` INT NULL DEFAULT NULL,
  `season` VARCHAR(20) NULL DEFAULT NULL,
  `site_id` INT NULL DEFAULT NULL,
  `site_name` VARCHAR(40) NULL DEFAULT NULL,
  `start_date` VARCHAR(20) NULL DEFAULT NULL,
  `start_date_gmt_offset` VARCHAR(10) NULL DEFAULT NULL,
  `start_date_raw` DATE NULL DEFAULT NULL,
  `start_datetime_gmt` DATETIME NULL DEFAULT NULL,
  `start_datetime_gmt_raw` DATETIME NULL DEFAULT NULL,
  `start_datetime_local` DATETIME NULL DEFAULT NULL,
  `start_time_gmt` TIME NULL DEFAULT NULL,
  `start_time_local` TIME NULL DEFAULT NULL,
  `team1_abbreviation` VARCHAR(20) NULL DEFAULT NULL,
  `team1_class_id` INT NULL DEFAULT NULL,
  `team1_country_id` INT NULL DEFAULT NULL,
  `team1_filename` VARCHAR(20) NULL DEFAULT NULL,
  `team1_id` INT NULL DEFAULT NULL,
  `team1_logo_alt_id` VARCHAR(20) NULL DEFAULT NULL,
  `team1_logo_espncdn` VARCHAR(20) NULL DEFAULT NULL,
  `team1_logo_object_id` INT NULL DEFAULT NULL,
  `team1_name` VARCHAR(40) NULL DEFAULT NULL,
  `team1_object_id` INT NULL DEFAULT NULL,
  `team1_short_name` VARCHAR(30) NULL DEFAULT NULL,
  `team2_abbreviation` VARCHAR(20) NULL DEFAULT NULL,
  `team2_class_id` INT NULL DEFAULT NULL,
  `team2_country_id` INT NULL DEFAULT NULL,
  `team2_filename` VARCHAR(20) NULL DEFAULT NULL,
  `team2_id` INT NULL DEFAULT NULL,
  `team2_logo_alt_id` VARCHAR(20) NULL DEFAULT NULL,
  `team2_logo_espncdn` VARCHAR(20) NULL DEFAULT NULL,
  `team2_logo_object_id` INT NULL DEFAULT NULL,
  `team2_name` VARCHAR(40) NULL DEFAULT NULL,
  `team2_object_id` INT NULL DEFAULT NULL,
  `team2_short_name` VARCHAR(30) NULL DEFAULT NULL,
  `tiebreaker_name` VARCHAR(20) NULL DEFAULT NULL,
  `tiebreaker_team_id` INT NULL DEFAULT NULL,
  `tiebreaker_type` INT NULL DEFAULT NULL,
  `time_zone` VARCHAR(20) NULL DEFAULT NULL,
  `toss_choice_team_id` INT NULL DEFAULT NULL,
  `toss_decision` VARCHAR(20) NULL DEFAULT NULL,
  `toss_decision_name` VARCHAR(20) NULL DEFAULT NULL,
  `toss_winner_team_id` INT NULL DEFAULT NULL,
  `town_aka` VARCHAR(20) NULL DEFAULT NULL,
  `town_area` VARCHAR(20) NULL DEFAULT NULL,
  `town_id` INT NULL DEFAULT NULL,
  `town_name` VARCHAR(20) NULL DEFAULT NULL,
  `tz_short_name` VARCHAR(20) NULL DEFAULT NULL,
  `url_component` VARCHAR(20) NULL DEFAULT NULL,
  `watch_espn_id` INT NULL DEFAULT NULL,
  `weather_location_code` VARCHAR(20) NULL DEFAULT NULL,
  `winner_team_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`playerofmatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`playerofmatch` (
  `match_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `player_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`playerofseries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`playerofseries` (
  `match_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `player_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`samples`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`samples` (
  `sample_date` INT NULL DEFAULT NULL,
  `sample_time` INT NULL DEFAULT NULL,
  `device_id` INT NULL DEFAULT NULL,
  `sample_value` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`seasons` (
  `match_id` INT NOT NULL,
  `season` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`series` (
  `match_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `class_name` VARCHAR(30) NULL DEFAULT NULL,
  `content_id` INT NOT NULL,
  `core_recreation_id` INT NOT NULL,
  `date` VARCHAR(30) NOT NULL,
  `end_date` VARCHAR(30) NOT NULL,
  `end_date_raw` DATE NOT NULL,
  `final_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `group_title` VARCHAR(30) NULL DEFAULT NULL,
  `major_trophy` INT NULL DEFAULT NULL,
  `match_number` INT NULL DEFAULT NULL,
  `match_title` VARCHAR(30) NULL DEFAULT NULL,
  `match_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `multiformat_pointstable` VARCHAR(10) NULL DEFAULT NULL,
  `number_of_hosts` INT NULL DEFAULT NULL,
  `number_of_matches` INT NULL DEFAULT NULL,
  `number_of_teams` INT NULL DEFAULT NULL,
  `object_id` INT NOT NULL,
  `points` INT NULL DEFAULT NULL,
  `primary_series` VARCHAR(10) NULL DEFAULT NULL,
  `replayed_date` VARCHAR(10) NULL DEFAULT NULL,
  `schedule_note` VARCHAR(10) NULL DEFAULT NULL,
  `score_module_position` INT NOT NULL,
  `season` VARCHAR(15) NOT NULL,
  `series_abbreviation` VARCHAR(30) NULL DEFAULT NULL,
  `series_category_id` INT NOT NULL,
  `series_category_name` VARCHAR(30) NOT NULL,
  `series_filename` VARCHAR(30) NULL DEFAULT NULL,
  `series_lead_abandoned` INT NOT NULL,
  `series_lead_cancelled` INT NOT NULL,
  `series_lead_how_won_name` VARCHAR(30) NULL DEFAULT NULL,
  `series_lead_lost` INT NOT NULL,
  `series_lead_result_name` VARCHAR(30) NULL DEFAULT NULL,
  `series_lead_team_name` VARCHAR(30) NULL DEFAULT NULL,
  `series_lead_total` INT NOT NULL,
  `series_lead_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `series_lead_won` INT NOT NULL,
  `series_long_description` VARCHAR(30) NULL DEFAULT NULL,
  `series_name` TEXT NULL DEFAULT NULL,
  `series_short_name` VARCHAR(45) NULL DEFAULT NULL,
  `series_status` VARCHAR(30) NULL DEFAULT NULL,
  `series_type_id` INT NOT NULL,
  `series_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `short_alternate_name` VARCHAR(30) NULL DEFAULT NULL,
  `site_id` INT NOT NULL,
  `slug` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` VARCHAR(30) NULL DEFAULT NULL,
  `start_date_raw` DATE NULL DEFAULT NULL,
  `team1_points` DOUBLE NULL DEFAULT NULL,
  `team2_points` DOUBLE NULL DEFAULT NULL,
  `tiebreaker_id` INT NULL DEFAULT NULL,
  `tiebreaker_name` VARCHAR(30) NULL DEFAULT NULL,
  `trophy_abbreviation` VARCHAR(30) NULL DEFAULT NULL,
  `trophy_class_id` INT NULL DEFAULT NULL,
  `trophy_country_id` INT NULL DEFAULT NULL,
  `trophy_id` INT NULL DEFAULT NULL,
  `trophy_name` VARCHAR(30) NULL DEFAULT NULL,
  `trophy_short_name` VARCHAR(30) NULL DEFAULT NULL,
  `url_component` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`, `core_recreation_id`, `object_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`squad_summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`squad_summary` (
  `match_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(40) NOT NULL,
  `age_days` INT NULL DEFAULT NULL,
  `age_years` INT NULL DEFAULT NULL,
  `alpha_name` VARCHAR(30) NULL DEFAULT NULL,
  `batting_hand` VARCHAR(40) NULL DEFAULT NULL,
  `batting_style` VARCHAR(40) NULL DEFAULT NULL,
  `batting_style_long` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_hand` VARCHAR(40) NULL DEFAULT NULL,
  `bowling_pacespin` VARCHAR(30) NULL DEFAULT NULL,
  `bowling_style` VARCHAR(30) NULL DEFAULT NULL,
  `bowling_style_long` VARCHAR(30) NULL DEFAULT NULL,
  `captain` TINYINT(1) NULL DEFAULT NULL,
  `card_long` VARCHAR(40) NULL DEFAULT NULL,
  `card_qualifier` VARCHAR(40) NULL DEFAULT NULL,
  `card_short` VARCHAR(40) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `keeper` TINYINT(1) NOT NULL,
  `known_as` VARCHAR(40) NOT NULL,
  `mobile_name` VARCHAR(40) NULL DEFAULT NULL,
  `object_id` INT NOT NULL,
  `player_id` INT NOT NULL,
  `player_primary_role` VARCHAR(30) NULL DEFAULT NULL,
  `player_style_id` DOUBLE NULL DEFAULT NULL,
  `player_type` INT NULL DEFAULT NULL,
  `player_type_name` VARCHAR(30) NULL DEFAULT NULL,
  `popular_name` VARCHAR(30) NULL DEFAULT NULL,
  `portrait_alt_id` VARCHAR(10) NULL DEFAULT NULL,
  `portrait_object_id` INT NULL DEFAULT NULL,
  `status_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`match_id`, `team_id`, `object_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`team_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`team_classes` (
  `id` INT NOT NULL,
  `class` INT NOT NULL,
  PRIMARY KEY (`id`, `class`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cricket`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cricket`.`teams` (
  `id` INT NOT NULL,
  `uid` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  `displayName` VARCHAR(45) NOT NULL,
  `shortDisplayName` VARCHAR(45) NOT NULL,
  `countryCode` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `isNational` TINYINT NOT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
